name: Auto Commit Test

on:
  schedule:
    - cron: "*/5 * * * *"   # Every 5 minutes
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make dummy change
        run: |
          echo "Last updated on $(date)" >> keep_alive.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add keep_alive.txt
          git commit -m "chore: auto commit $(date)" || echo "No changes to commit"

      - name: Pull & Push changes
        run: |
          git pull --rebase origin main
          git push origin HEAD:main
